workflows:
  android-build:
    name: Android APK Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 16
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Initialize React Native Android
        script: |
          npx react-native init KegScanner --template react-native@^0.72.0 --skip-install
          cp -r KegScanner/android ./
          cp package.json ./
          npm install
      - name: Fix react-native-camera variant conflict
        script: |
          cat > temp_config.txt << 'EOF'

          configurations.all {
              resolutionStrategy {
                  eachDependency { details ->
                      if (details.requested.name == "react-native-camera") {
                          details.useTarget group: details.requested.group, name: details.requested.name, version: details.requested.version
                      }
                  }
              }
          }
          EOF
          
          head -1 android/app/build.gradle > temp_build.gradle
          cat temp_config.txt >> temp_build.gradle
          tail -n +2 android/app/build.gradle >> temp_build.gradle
          mv temp_build.gradle android/app/build.gradle
          rm temp_config.txt
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: List available gradle tasks
        script: |
          cd android
          echo "=== Available assemble tasks ==="
          ./gradlew tasks --all | grep -i assemble
          echo "=== Available build variants ==="
          ./gradlew tasks | grep -E "(assemble|build)"
      - name: Try building Android APK
        script: |
          cd android
          echo "=== Attempting MLKit Release build ==="
          if ./gradlew assembleMlkitRelease --stacktrace; then
            echo "✅ MLKit Release build successful"
          else
            echo "❌ MLKit Release build failed, trying alternatives..."
            
            echo "=== Attempting General Release build ==="
            if ./gradlew assembleGeneralRelease --stacktrace; then
              echo "✅ General Release build successful"
            else
              echo "❌ General Release build failed, trying standard release..."
              
              echo "=== Attempting standard Release build ==="
              if ./gradlew assembleRelease --stacktrace; then
                echo "✅ Standard Release build successful"
              else
                echo "❌ All build attempts failed"
                exit 1
              fi
            fi
          fi
      - name: Find generated APK files
        script: |
          echo "=== Looking for APK files ==="
          if [ -d "android/app/build/outputs" ]; then
            find android/app/build/outputs -name "*.apk" -type f -exec ls -lh {} \;
            echo "=== Directory structure ==="
            find android/app/build/outputs -type d
          else
            echo "❌ Build outputs directory doesn't exist - build may have failed"
            echo "=== Checking if android directory exists ==="
            ls -la android/app/
            if [ -d "android/app/build" ]; then
              echo "=== Contents of build directory ==="
              find android/app/build -name "*.apk" -o -name "*outputs*" -type d
            fi
          fi
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - shantu.hasko@ab-inbev.com
        notify:
          success: true
