workflows:
  expo-android:
    name: Expo Android Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      node: 16
      npm: 8
    scripts:
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli@latest
          npm install -g eas-cli@latest
      - name: Install project dependencies
        script: |
          npm install
      - name: Build APK with Expo
        script: |
          npx expo install --fix
          npx expo export --platform android
          npx expo run:android --variant release
    artifacts:
      - "*.apk"
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - shantu.hasko@ab-inbev.com
        notify:
          success: true
