workflows:
  android-build:
    name: Android APK Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 16
      xcode: latest
    scripts:
      - name: Create React Native project with correct structure
        script: |
          # Create a proper React Native project
          npx react-native@0.72.10 init KegBatchScanner --version 0.72.10
          
          # Copy our custom files into the project
          cp package.json KegBatchScanner/
          cp App.js KegBatchScanner/
          cp index.js KegBatchScanner/
          cp app.json KegBatchScanner/
          cp metro.config.js KegBatchScanner/
          cp babel.config.js KegBatchScanner/
          
          # Move into the project directory
          cd KegBatchScanner
          
          # Install our dependencies
          npm install
      - name: Set up Android SDK and build
        script: |
          cd KegBatchScanner
          
          # Set up local.properties
          echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties
          
          # List what build variants are actually available
          echo "=== Available build tasks ==="
          cd android && ./gradlew tasks --all | grep -i assemble
          
          # Check if react-native-camera has variants
          echo "=== Checking react-native-camera variants ==="
          ./gradlew :react-native-camera:tasks | grep -i assemble || true
      - name: Build the APK
        script: |
          cd KegBatchScanner/android
          
          # Try different build approaches
          echo "=== Building APK ==="
          
          if ./gradlew assembleRelease --stacktrace --info; then
            echo "✅ Standard release build successful"
          elif ./gradlew assembleMlkitRelease --stacktrace --info; then
            echo "✅ MLKit release build successful"  
          elif ./gradlew assembleGeneralRelease --stacktrace --info; then
            echo "✅ General release build successful"
          else
            echo "❌ All build variants failed"
            echo "=== Available variants ==="
            ./gradlew tasks | grep assemble
            exit 1
          fi
      - name: Find and verify APK
        script: |
          cd KegBatchScanner
          echo "=== Searching for APK files ==="
          find . -name "*.apk" -type f -exec ls -lh {} \;
          
          echo "=== Build output directory structure ==="
          if [ -d "android/app/build/outputs" ]; then
            find android/app/build/outputs -type f -name "*.apk"
          else
            echo "No outputs directory found"
            ls -la android/app/build/ || echo "No build directory"
          fi
    artifacts:
      - KegBatchScanner/android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - shantu.hasko@ab-inbev.com
        notify:
          success: true
