workflows:
  android-build:
    name: Android APK Build
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      vars:
        PACKAGE_NAME: "com.kegbatchscanner"
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
      node: 16
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Build APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - your-email@domain.com
        notify:
          success: true
