workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 16
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Initialize React Native Android
        script: |
          npx react-native init KegScanner --template react-native@^0.72.0 --skip-install
          cp -r KegScanner/android ./
          cp package.json ./
          npm install
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - shantu.hasko@ab-inbev.com
        notify:
          success: true
