workflows:
  android-build:
    name: Android APK Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 16
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Initialize React Native Android
        script: |
          npx react-native init KegScanner --template react-native@^0.72.0 --skip-install
          cp -r KegScanner/android ./
          cp package.json ./
          npm install
      - name: Fix react-native-camera variant conflict
        script: |
          # Insert variant selection configuration into app/build.gradle
          sed -i '/apply plugin: "com.android.application"/a\
          \
          configurations.all {\
              resolutionStrategy {\
                  eachDependency { details ->\
                      if (details.requested.name == "react-native-camera") {\
                          details.useTarget group: details.requested.group, name: details.requested.name, version: details.requested.version\
                      }\
                  }\
              }\
          }' android/app/build.gradle
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: List available tasks
        script: |
          cd android
          ./gradlew tasks --all | grep -i assemble
      - name: Build Android APK with MLKit variant
        script: |
          cd android
          ./gradlew assembleMlkitRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - shantu.hasko@ab-inbev.com
        notify:
          success: true
