workflows:
  android-build:
    name: Android APK Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 16
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Initialize React Native Android
        script: |
          npx react-native init KegScanner --template react-native@^0.72.0 --skip-install
          cp -r KegScanner/android ./
          cp package.json ./
          npm install
      - name: Fix react-native-camera variant conflict
        script: |
          cat > temp_config.txt << 'EOF'

          configurations.all {
              resolutionStrategy {
                  eachDependency { details ->
                      if (details.requested.name == "react-native-camera") {
                          details.useTarget group: details.requested.group, name: details.requested.name, version: details.requested.version
                      }
                  }
              }
          }
          EOF
          
          head -1 android/app/build.gradle > temp_build.gradle
          cat temp_config.txt >> temp_build.gradle
          tail -n +2 android/app/build.gradle >> temp_build.gradle
          mv temp_build.gradle android/app/build.gradle
          rm temp_config.txt
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: List available tasks
        script: |
          cd android
          ./gradlew tasks --all | grep -i assemble
      - name: Build Android APK with MLKit variant
        script: |
          cd android
          ./gradlew assembleMlkitRelease
      - name: Find generated APK files
        script: |
          echo "=== Looking for APK files ==="
          find android/app/build/outputs -name "*.apk" -type f
          echo "=== Directory structure ==="
          ls -la android/app/build/outputs/
          if [ -d "android/app/build/outputs/apk" ]; then
            echo "=== APK directory contents ==="
            find android/app/build/outputs/apk -type f
          fi
    artifacts:
      - android/app/build/outputs/apk/**/*.apk
      - android/app/build/outputs/apk/**/release/*.apk
      - android/app/build/outputs/apk/mlkit/release/*.apk
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - shantu.hasko@ab-inbev.com
        notify:
          success: true
